# Generated by Django 6.1 on 2026-08-20 10:47

import apps.brands.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_workspacemember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('palette', models.JSONField(blank=True, default=apps.brands.models.default_palette)),
                ('fonts', models.JSONField(blank=True, default=apps.brands.models.default_fonts)),
                ('layout_preference', models.CharField(choices=[('agency_column', 'Agency column'), ('jil_sander', 'Minimal centred'), ('cos_split', 'Split tone'), ('data_hero', 'Data hero'), ('ghost_word', 'Ghost word'), ('vs_table', 'Versus table')], default='agency_column', max_length=64)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('cta_keyword', models.CharField(blank=True, max_length=100)),
                ('brand_tone', models.CharField(blank=True, max_length=255)),
                ('instagram_handle', models.CharField(blank=True, max_length=100)),
                ('competitors', models.JSONField(blank=True, default=list)),
                ('logo_url', models.URLField(blank=True, max_length=1000)),
                ('logo_storage_path', models.CharField(blank=True, max_length=1000)),
                ('logo_file_name', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('show_logo_on_posters', models.BooleanField(default=False)),
                ('show_phone_on_posters', models.BooleanField(default=False)),
                ('creative_brain', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_brands', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'brands',
                'ordering': ['-is_default', 'name'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='brands_workspa_e59e0a_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'name'), name='unique_brand_name_per_workspace')],
            },
        ),
    ]
