# Generated by Django 6.1 on 2026-08-22 06:00

"""
The business profile onboarding collects but had nowhere to put.

Every field is optional and blank-defaulted: existing brands are complete
without them, so there is nothing to backfill and no row to rewrite.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='audience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='products_services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='brand',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='brand',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
