# Generated by Django 6.1 on 2026-09-01 15:41
#
# Blank now means "no preference — rotate the template catalogue". Every
# existing row holding 'agency_column' holds the old DEFAULT, not a choice:
# the brand kit UI never exposed the field, so nobody could have picked it.
# Clearing those rows unpins every brand's posters from the one skeleton.

from django.db import migrations, models


def clear_phantom_preference(apps, schema_editor):
    Brand = apps.get_model('brands', 'Brand')
    Brand.objects.filter(layout_preference='agency_column').update(
        layout_preference=''
    )


def restore_old_default(apps, schema_editor):
    Brand = apps.get_model('brands', 'Brand')
    Brand.objects.filter(layout_preference='').update(
        layout_preference='agency_column'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_brand_brain_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='layout_preference',
            field=models.CharField(blank=True, choices=[('agency_column', 'Agency column'), ('jil_sander', 'Minimal centred'), ('cos_split', 'Split tone'), ('data_hero', 'Data hero'), ('ghost_word', 'Ghost word'), ('vs_table', 'Versus table')], default='', max_length=64),
        ),
        migrations.RunPython(clear_phantom_preference, restore_old_default),
    ]
