# Generated by Django 6.1 on 2026-09-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_alter_brand_layout_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='guardrails',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
