# Generated by Django 6.1 on 2026-08-21 10:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('knowledge', '0001_initial'),
        ('workspaces', '0002_workspacemember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandInspiration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspiration_type', models.CharField(choices=[('IMAGE', 'Image'), ('SCREENSHOT', 'Screenshot'), ('URL', 'URL'), ('WEB_PAGE', 'Web page'), ('POST', 'Social post'), ('REEL', 'Reel / short video'), ('VIDEO', 'Video'), ('AD', 'Advertisement'), ('PIN', 'Pinboard pin'), ('COMPETITOR', 'Competitor reference'), ('REFERENCE', 'General reference'), ('MOODBOARD', 'Moodboard'), ('OTHER', 'Other')], default='REFERENCE', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('annotation', models.TextField(blank=True)),
                ('reference_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('storage_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('external_platform', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('usage_scope', models.CharField(choices=[('FULL_REFERENCE', 'Use the entire reference'), ('SPECIFIC_ELEMENTS', 'Use only the named elements')], default='FULL_REFERENCE', max_length=20)),
                ('focus_areas', models.JSONField(blank=True, default=list)),
                ('analysis_status', models.CharField(choices=[('NOT_ANALYSED', 'Not analysed'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('NEEDS_REVIEW', 'Needs review'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='NOT_ANALYSED', max_length=20)),
                ('lifecycle_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspirations_archived', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspirations', to='brands.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspirations_created', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspirations', to='knowledge.brandsource')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_inspirations', to='workspaces.marketingworkspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspirationSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('TYPOGRAPHY', 'Typography'), ('COLOR', 'Colour'), ('LAYOUT', 'Layout'), ('COMPOSITION', 'Composition'), ('IMAGERY', 'Imagery'), ('PHOTOGRAPHY', 'Photography'), ('ILLUSTRATION', 'Illustration'), ('MOTION', 'Motion'), ('PACING', 'Pacing'), ('TONE', 'Tone of voice'), ('COPY_STYLE', 'Copy style'), ('HOOK', 'Hook'), ('CTA', 'Call to action'), ('STRUCTURE', 'Structure'), ('MOOD', 'Mood'), ('BRANDING', 'Branding'), ('OTHER', 'Other')], max_length=20)),
                ('attribute', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True)),
                ('sentiment', models.CharField(choices=[('LIKED', 'Liked'), ('DISLIKED', 'Disliked'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=10)),
                ('weight', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('confidence', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('origin', models.CharField(choices=[('USER', 'Stated by a user'), ('AI', 'Inferred by a model')], default='USER', max_length=10)),
                ('user_confirmation', models.CharField(choices=[('CONFIRMED', 'Confirmed by a user'), ('PENDING', 'Awaiting user review'), ('REJECTED', 'Rejected by a user')], default='PENDING', max_length=10)),
                ('extracted_by_provider', models.CharField(blank=True, max_length=100)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspiration_signals_confirmed', to=settings.AUTH_USER_MODEL)),
                ('conflicts_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contradicted_by', to='inspirations.inspirationsignal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspiration_signals_created', to=settings.AUTH_USER_MODEL)),
                ('inspiration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='inspirations.brandinspiration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='brandinspiration',
            index=models.Index(fields=['workspace', 'brand'], name='inspiration_workspa_56274b_idx'),
        ),
        migrations.AddIndex(
            model_name='brandinspiration',
            index=models.Index(fields=['brand', 'lifecycle_status'], name='inspiration_brand_i_8de475_idx'),
        ),
        migrations.AddIndex(
            model_name='inspirationsignal',
            index=models.Index(fields=['inspiration', 'category'], name='inspiration_inspira_7ba21a_idx'),
        ),
        migrations.AddIndex(
            model_name='inspirationsignal',
            index=models.Index(fields=['inspiration', 'origin'], name='inspiration_inspira_e5dbcd_idx'),
        ),
        migrations.AddConstraint(
            model_name='inspirationsignal',
            constraint=models.UniqueConstraint(condition=models.Q(('origin', 'AI')), fields=('inspiration', 'category', 'attribute'), name='uniq_ai_signal_per_inspiration_attribute'),
        ),
    ]
