# Generated by Django 6.1 on 2026-08-21 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _normalize(text):
    """Frozen copy of `normalize_signal_text` at the time of this migration.

    Deliberately not imported from the model: a migration has to keep doing
    what it did the day it was written, and importing would silently rewrite
    history if the folding rule is ever changed.
    """
    if not text:
        return ''
    return ' '.join(str(text).split()).casefold()


def backfill_normalized_columns(apps, schema_editor):
    """Fold existing rows before the uniqueness rules start depending on them.

    The constraints added below are keyed on `normalized_attribute`, so every
    row must have one first; without this they would all collide on the empty
    string.
    """
    InspirationSignal = apps.get_model('inspirations', 'InspirationSignal')
    batch = []
    for signal in InspirationSignal.objects.all().iterator():
        signal.normalized_attribute = _normalize(signal.attribute)
        signal.normalized_value = _normalize(signal.value)
        batch.append(signal)
        if len(batch) >= 500:
            InspirationSignal.objects.bulk_update(
                batch, ['normalized_attribute', 'normalized_value']
            )
            batch = []
    if batch:
        InspirationSignal.objects.bulk_update(
            batch, ['normalized_attribute', 'normalized_value']
        )


def drop_normalized_columns(apps, schema_editor):
    """Nothing to undo: the columns are removed by reversing the AddFields."""


class Migration(migrations.Migration):

    dependencies = [
        ('inspirations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inspirationsignal',
            name='uniq_ai_signal_per_inspiration_attribute',
        ),
        migrations.AddField(
            model_name='inspirationsignal',
            name='normalized_attribute',
            field=models.CharField(blank=True, default='', max_length=765),
        ),
        migrations.AddField(
            model_name='inspirationsignal',
            name='normalized_value',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inspirationsignal',
            name='superseded_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inspirationsignal',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='inspirations.inspirationsignal'),
        ),
        migrations.AddField(
            model_name='inspirationsignal',
            name='superseded_reason',
            field=models.CharField(blank=True, choices=[('SUPERSEDED_BY_NEWER_USER_SIGNAL', 'Replaced by a newer stated preference'), ('SUPERSEDED_BY_CONFIRMED_AI_DIRECTION', 'A user accepted a contradicting inference'), ('SUPERSEDED_BY_NEWER_AI_INFERENCE', 'Replaced by a newer inference after a human had ruled on this one')], default='', max_length=48),
        ),
        migrations.RunPython(
            backfill_normalized_columns, drop_normalized_columns, elidable=True
        ),
        migrations.AddIndex(
            model_name='inspirationsignal',
            index=models.Index(fields=['inspiration', 'category', 'normalized_attribute'], name='inspiration_inspira_30d3c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='inspirationsignal',
            constraint=models.UniqueConstraint(condition=models.Q(('origin', 'USER'), ('superseded_at__isnull', True), ('user_confirmation', 'CONFIRMED')), fields=('inspiration', 'category', 'normalized_attribute'), name='uniq_authoritative_user_signal'),
        ),
        migrations.AddConstraint(
            model_name='inspirationsignal',
            constraint=models.UniqueConstraint(condition=models.Q(('origin', 'AI'), ('superseded_at__isnull', True)), fields=('inspiration', 'category', 'normalized_attribute'), name='uniq_active_ai_signal'),
        ),
        migrations.AddConstraint(
            model_name='inspirationsignal',
            constraint=models.CheckConstraint(condition=models.Q(('superseded_by', models.F('id')), _negated=True), name='inspiration_signal_no_self_supersession'),
        ),
    ]
