# Generated by Django 6.1 on 2026-09-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspirations', '0006_brand_ambassador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandinspiration',
            name='inspiration_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('SCREENSHOT', 'Screenshot'), ('URL', 'URL'), ('WEB_PAGE', 'Web page'), ('POST', 'Social post'), ('REEL', 'Reel / short video'), ('VIDEO', 'Video'), ('AD', 'Advertisement'), ('PIN', 'Pinboard pin'), ('COMPETITOR', 'Competitor reference'), ('REFERENCE', 'General reference'), ('MOODBOARD', 'Moodboard'), ('TEXT', 'Text / copy'), ('BRAND_TEMPLATE', 'Brand template'), ('BRAND_AMBASSADOR', 'Brand ambassador'), ('BRAND_PRODUCT', 'Product photo'), ('OTHER', 'Other')], default='REFERENCE', max_length=20),
        ),
    ]
