# Generated by Django 6.1 on 2026-08-11 10:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignROI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=255)),
                ('roi_multiplier', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_rois', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'analytics_campaign_roi',
                'unique_together': {('workspace', 'campaign_name')},
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reach', models.IntegerField(default=0)),
                ('engagement', models.IntegerField(default=0)),
                ('posts_published', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'analytics_daily_metrics',
                'unique_together': {('workspace', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PlatformPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=50)),
                ('reach', models.IntegerField(default=0)),
                ('engagement', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('roi_multiplier', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_performance', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'analytics_platform_performance',
                'unique_together': {('workspace', 'platform')},
            },
        ),
    ]
