# Generated by Django 6.1 on 2026-09-01 10:57

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('brands', '0004_brand_brain_health'),
        ('content', '0002_contentitem_layout_config_contentitem_layout_plugin'),
        ('engagement', '0001_initial'),
        ('publishing', '0003_publishingjob_content_item'),
        ('social_accounts', '0001_initial'),
        ('workspaces', '0005_workspace_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('handle', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('CONVERTED', 'Converted'), ('DISQUALIFIED', 'Disqualified')], default='NEW', max_length=20)),
                ('source', models.CharField(default='ENGAGEMENT', max_length=80)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('estimated_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth_leads', to='brands.brand')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth_leads_created', to=settings.AUTH_USER_MODEL)),
                ('engagement_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth_lead', to='engagement.engagementitem')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_leads', to='workspaces.marketingworkspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('X_API', 'X API'), ('YOUTUBE_API', 'YouTube API'), ('AUDITABLE_IMPORT', 'Auditable import')], max_length=32)),
                ('source_record_id', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=50)),
                ('external_post_id', models.CharField(blank=True, max_length=255)),
                ('campaign_name', models.CharField(blank=True, max_length=255)),
                ('impressions', models.PositiveBigIntegerField(default=0)),
                ('reach', models.PositiveBigIntegerField(default=0)),
                ('engagement', models.PositiveBigIntegerField(default=0)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('conversions', models.PositiveBigIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('revenue', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('observed_at', models.DateTimeField()),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_observations', to='brands.brand')),
                ('content_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_observations', to='content.contentitem')),
                ('ingested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_observations_ingested', to=settings.AUTH_USER_MODEL)),
                ('publishing_job_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_observations', to='publishing.publishingjobitem')),
                ('social_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_observations', to='social_accounts.socialconnection')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_observations', to='workspaces.marketingworkspace')),
            ],
            options={
                'ordering': ['-observed_at', '-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceSyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=64)),
                ('observed_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_sync_runs', to=settings.AUTH_USER_MODEL)),
                ('social_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_sync_runs', to='social_accounts.socialconnection')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_sync_runs', to='workspaces.marketingworkspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=80)),
                ('external_event_id', models.CharField(max_length=255)),
                ('campaign_name', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('occurred_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_events', to='content.contentitem')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_events', to='analytics.growthlead')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_events_recorded', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_events', to='workspaces.marketingworkspace')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='growthlead',
            index=models.Index(fields=['workspace', 'status', '-created_at'], name='analytics_g_workspa_75734b_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceobservation',
            index=models.Index(fields=['workspace', '-observed_at'], name='analytics_p_workspa_7223db_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceobservation',
            index=models.Index(fields=['workspace', 'platform', '-observed_at'], name='analytics_p_workspa_e933cd_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceobservation',
            index=models.Index(fields=['workspace', 'content_item'], name='analytics_p_workspa_25002e_idx'),
        ),
        migrations.AddConstraint(
            model_name='performanceobservation',
            constraint=models.UniqueConstraint(fields=('workspace', 'source', 'source_record_id'), name='uniq_performance_source_record'),
        ),
        migrations.AddConstraint(
            model_name='performanceobservation',
            constraint=models.CheckConstraint(condition=models.Q(('revenue__gte', 0), ('spend__gte', 0)), name='performance_money_non_negative'),
        ),
        migrations.AddIndex(
            model_name='performancesyncrun',
            index=models.Index(fields=['workspace', 'status', '-created_at'], name='analytics_p_workspa_1cb5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueevent',
            index=models.Index(fields=['workspace', '-occurred_at'], name='analytics_r_workspa_c68b47_idx'),
        ),
        migrations.AddConstraint(
            model_name='revenueevent',
            constraint=models.UniqueConstraint(fields=('workspace', 'source', 'external_event_id'), name='uniq_revenue_source_event'),
        ),
        migrations.AddConstraint(
            model_name='revenueevent',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='revenue_amount_non_negative'),
        ),
    ]
