# Generated by Django 6.1 on 2026-08-11 10:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('previous_state', models.CharField(blank=True, max_length=100, null=True)),
                ('next_state', models.CharField(blank=True, max_length=100, null=True)),
                ('result', models.CharField(max_length=50)),
                ('error', models.TextField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
    ]
