# Generated by Django 6.1 on 2026-08-21 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('workspaces', '0002_workspacemember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandOnboarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_stage', models.CharField(choices=[('BASICS', 'Brand basics'), ('KNOWLEDGE', 'Upload knowledge'), ('INSPIRATIONS', 'Add inspirations'), ('CALIBRATION', 'Teach Scaleezy your taste'), ('FIRST_GENERATION', 'Create your first content'), ('DONE', 'Done')], default='BASICS', max_length=20)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('READY_FOR_GENERATION', 'Ready for generation'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=24)),
                ('skipped_steps', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='brands.brand')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_onboardings', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'brand_onboarding',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationDirection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_id', models.UUIDField(db_index=True)),
                ('label', models.CharField(max_length=8)),
                ('tests_dimension', models.CharField(max_length=64)),
                ('tested_attributes', models.JSONField(blank=True, default=dict)),
                ('headline', models.CharField(blank=True, max_length=500)),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.TextField(blank=True)),
                ('preview_url', models.URLField(blank=True, max_length=1000)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('brain_version', models.CharField(blank=True, max_length=64)),
                ('verdict', models.CharField(choices=[('PENDING', 'Awaiting reaction'), ('LIKED', 'Like'), ('NOT_US', 'Not us'), ('ADJUSTED', 'Adjust')], default='PENDING', max_length=10)),
                ('adjustment_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('learning_event_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_directions', to='brands.brand')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_decisions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'calibration_directions',
                'ordering': ['round_id', 'label'],
                'indexes': [models.Index(fields=['brand', '-created_at'], name='calibration_brand_i_9cc059_idx')],
            },
        ),
    ]
