# Generated by Django 6.1 on 2026-08-20 11:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_workspacemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(help_text="Matches the adapter's key.", unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('capabilities', models.JSONField(default=list, help_text='Capability values this provider can serve.')),
                ('default_model', models.CharField(blank=True, max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, help_text='Indicative cost per generation, used for BEST_OF scoring.', max_digits=10)),
                ('docs_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_providers',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability', models.CharField(choices=[('TEXT', 'Copy (headline, caption, hashtags)'), ('IMAGE', 'Image generation'), ('IMAGE_ANALYSIS', 'Image analysis'), ('VIDEO', 'Video generation')], max_length=32)),
                ('content_item_id', models.UUIDField(blank=True, null=True)),
                ('units', models.PositiveIntegerField(default=1)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('strategy', models.CharField(blank=True, max_length=20)),
                ('selected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage', to='ai.aiprovider')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'ai_usage_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='ai_usage_lo_workspa_aefaca_idx'), models.Index(fields=['workspace', 'capability'], name='ai_usage_lo_workspa_18457e_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAIProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('credentials_encrypted', models.TextField(blank=True)),
                ('model_override', models.CharField(blank=True, max_length=100)),
                ('max_cost_per_generation', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_ok', models.BooleanField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='ai.aiprovider')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_providers', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'workspace_ai_providers',
                'ordering': ['provider__display_name'],
                'unique_together': {('workspace', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAIRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability', models.CharField(choices=[('TEXT', 'Copy (headline, caption, hashtags)'), ('IMAGE', 'Image generation'), ('IMAGE_ANALYSIS', 'Image analysis'), ('VIDEO', 'Video generation')], max_length=32)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower runs first.')),
                ('enabled', models.BooleanField(default=True)),
                ('strategy', models.CharField(choices=[('FAILOVER', 'Failover — first healthy provider wins'), ('BEST_OF', 'Best of — run all, keep the highest scoring'), ('ROUND_ROBIN', 'Round robin — spread load and spend')], default='FAILOVER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='ai.aiprovider')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_routes', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'workspace_ai_routes',
                'ordering': ['capability', 'priority'],
                'unique_together': {('workspace', 'capability', 'provider')},
            },
        ),
    ]
