# Generated by Django 6.1 on 2026-08-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_seed_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='capability',
            field=models.CharField(choices=[('TEXT', 'Copy (headline, caption, hashtags)'), ('IMAGE', 'Image generation'), ('IMAGE_ANALYSIS', 'Image analysis'), ('VIDEO', 'Video generation'), ('EMBEDDING', 'Text embedding (feedback similarity)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='workspaceairoute',
            name='capability',
            field=models.CharField(choices=[('TEXT', 'Copy (headline, caption, hashtags)'), ('IMAGE', 'Image generation'), ('IMAGE_ANALYSIS', 'Image analysis'), ('VIDEO', 'Video generation'), ('EMBEDDING', 'Text embedding (feedback similarity)')], max_length=32),
        ),
    ]
