# Generated by Django 6.1 on 2026-08-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_workspace_provider_capabilities'),
        ('workspaces', '0005_workspace_kind'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workspaceairoute',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workspaceairoute',
            name='model_override',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='workspaceairoute',
            unique_together={('workspace', 'capability', 'provider', 'model_override')},
        ),
    ]
