# Generated by Django 6.1 on 2026-09-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_refresh_gemini_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusagelog',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
