# Generated by Django 6.1 on 2026-08-20 13:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_workspacemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('monthly_generations', models.PositiveIntegerField(default=100, help_text='Generations per period. 0 = unlimited.')),
                ('monthly_spend_cap', models.DecimalField(decimal_places=2, default=0, help_text='Spend ceiling per period. 0 = uncapped.', max_digits=10)),
                ('max_scheduled_jobs', models.PositiveIntegerField(default=0, help_text='Concurrently scheduled publishing jobs. 0 = unlimited.')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'billing_plans',
                'ordering': ['position', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('generations_override', models.PositiveIntegerField(blank=True, null=True)),
                ('spend_cap_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'billing_subscriptions',
            },
        ),
    ]
