# Generated by Django 6.1 on 2026-08-21 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('workspaces', '0002_workspacemember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('WEBSITE', 'Website'), ('URL', 'URL'), ('PDF', 'PDF'), ('DOCUMENT', 'Document'), ('TRANSCRIPT', 'Transcript'), ('MOM', 'Minutes of Meeting'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('NOTE', 'Note'), ('EMAIL_EXPORT', 'Email Export'), ('PRODUCT_DOC', 'Product Documentation'), ('SALES_CALL', 'Sales Call'), ('CUSTOMER_CALL', 'Customer Call'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('storage_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('NEEDS_REVIEW', 'Needs Review'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], default='UPLOADED', max_length=20)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sources', to='brands.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_sources_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sources', to='workspaces.marketingworkspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memory_type', models.CharField(choices=[('FACT', 'Fact'), ('BRAND_CANON', 'Brand Canon'), ('PRODUCT_TRUTH', 'Product Truth'), ('FOUNDER_POV', 'Founder POV'), ('POSITIONING_SIGNAL', 'Positioning Signal'), ('BUYER_PAIN', 'Buyer Pain'), ('OBJECTION', 'Objection'), ('EVIDENCE', 'Evidence'), ('DECISION', 'Decision'), ('CONTENT_IDEA', 'Content Idea'), ('CAMPAIGN_CONTEXT', 'Campaign Context'), ('ACTION_ITEM', 'Action Item'), ('CONFLICT', 'Conflict')], max_length=30)),
                ('content', models.TextField()),
                ('normalized_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('scope', models.CharField(choices=[('ASSET', 'Asset'), ('CAMPAIGN', 'Campaign'), ('BRAND', 'Brand'), ('TENANT', 'Tenant')], default='BRAND', max_length=20)),
                ('permanence', models.CharField(choices=[('TEMPORARY', 'Temporary'), ('EMERGING', 'Emerging'), ('PERMANENT', 'Permanent')], default='EMERGING', max_length=20)),
                ('status', models.CharField(choices=[('CANDIDATE', 'Candidate'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded'), ('EXPIRED', 'Expired')], default='CANDIDATE', max_length=20)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=100, null=True)),
                ('extracted_by_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='brands.brand')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='knowledge.brandmemory')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='workspaces.marketingworkspace')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_memories', to='knowledge.brandsource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
