# Generated by Django 6.1 on 2026-08-20 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempted_username', models.CharField(blank=True, max_length=255)),
                ('event', models.CharField(choices=[('LOGIN_SUCCESS', 'Login succeeded'), ('LOGIN_FAILED', 'Login failed'), ('TOKEN_REFRESH', 'Token refreshed'), ('TOKEN_REFRESH_FAILED', 'Token refresh failed'), ('LOGOUT', 'Logged out'), ('ACCESS_DENIED', 'Access denied')], max_length=32)),
                ('succeeded', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='auth_audit__created_733f79_idx'), models.Index(fields=['user', '-created_at'], name='auth_audit__user_id_f03ae9_idx'), models.Index(fields=['event', '-created_at'], name='auth_audit__event_cc9003_idx')],
            },
        ),
    ]
