/**
 * One place that decides how a public marketing page describes itself.
 *
 * Three audiences read these pages and they want different things:
 *
 *  - **Search engines (SEO)** want a unique title and description per URL, a
 *    canonical link, a real heading hierarchy and internal links between
 *    related pages.
 *  - **Answer engines (AEO)** — featured snippets, voice assistants — want the
 *    question asked in the user's own words and answered immediately after, in
 *    a couple of sentences, backed by FAQPage structured data.
 *  - **Generative engines (GEO)** — assistants that summarise rather than link
 *    — want unambiguous entity names, concrete specifics and self-contained
 *    sentences that survive being quoted away from their page.
 *
 * All three are served by the same discipline: say one true, specific thing per
 * block, and mark it up so a machine can tell what it is. Nothing here invents
 * a claim the product cannot support.
 */

/**
 * Absolute origin for canonical and og:url. Absolute URLs are required —
 * a relative canonical is ignored, and a relative og:image will not render in
 * any social preview.
 *
 * Configurable so pointing a custom domain at this deployment is an
 * environment change. `public/sitemap.xml` is static and carries the same
 * origin, so it has to be updated alongside a domain move.
 */
export const SITE_URL = (
  import.meta.env["VITE_SITE_URL"] ?? "https://scaleezy-marketing-hub.vercel.app"
).replace(/\/+$/, "");

export const SITE_NAME = "Scaleezy Marketing Hub";

/** Default social card. Generated by scripts/build-og-images.mjs. */
export const DEFAULT_OG_IMAGE = "/og/og-default.png";

export function absoluteUrl(path: string): string {
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}

export interface MarketingPageSeo {
  /** The <title>. Unique per URL, front-loaded with the page's own subject. */
  title: string;
  /** The meta description. One sentence, 140-160 characters, no boilerplate. */
  description: string;
  /** Path only, e.g. "/how-it-works". Becomes canonical and og:url. */
  path: string;
  /** Path to the social card for this page. */
  image?: string;
  /**
   * Structured data for this page. Emitted as JSON-LD by <JsonLd>, not here —
   * TanStack's head() takes meta and links, and script children are simpler to
   * keep honest when they render with the page body.
   */
  keywords?: readonly string[];
}

/**
 * Builds the `head()` payload for a public page.
 *
 * og:type, twitter:card and twitter:site come from __root.tsx and are not
 * repeated; duplicate og tags are a common cause of a wrong social preview.
 */
export function marketingHead(seo: MarketingPageSeo) {
  const url = absoluteUrl(seo.path);
  const image = absoluteUrl(seo.image ?? DEFAULT_OG_IMAGE);

  return {
    meta: [
      { title: seo.title },
      { name: "description", content: seo.description },
      ...(seo.keywords?.length ? [{ name: "keywords", content: seo.keywords.join(", ") }] : []),
      { property: "og:title", content: seo.title },
      { property: "og:description", content: seo.description },
      { property: "og:url", content: url },
      { property: "og:image", content: image },
      { property: "og:site_name", content: SITE_NAME },
      { name: "twitter:title", content: seo.title },
      { name: "twitter:description", content: seo.description },
      { name: "twitter:image", content: image },
      // The marketing pages are the only ones that should be indexed; the app
      // itself is behind auth and /login already sets noindex.
      { name: "robots", content: "index, follow, max-image-preview:large" },
    ],
    links: [{ rel: "canonical", href: url }],
  };
}

/* ------------------------------------------------------------------ */
/* Structured data                                                     */
/* ------------------------------------------------------------------ */

/**
 * Who Scaleezy is. Emitted once, on the home page, so the entity is defined in
 * one place — repeating a slightly different Organization on every page is how
 * a knowledge panel ends up with conflicting facts.
 */
export function organizationSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": `${SITE_URL}/#organization`,
    name: "Scaleezy",
    url: SITE_URL,
    logo: absoluteUrl("/brand/scaleezy-wordmark.webp"),
    description:
      "Scaleezy builds brand-aware marketing software that generates, reviews and publishes social content under human approval.",
  };
}

export function softwareApplicationSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    "@id": `${SITE_URL}/#software`,
    name: SITE_NAME,
    applicationCategory: "BusinessApplication",
    applicationSubCategory: "Social Media Marketing Software",
    operatingSystem: "Web browser",
    url: SITE_URL,
    publisher: { "@id": `${SITE_URL}/#organization` },
    description:
      "An AI social media marketing platform that learns a brand from its own documents and references, drafts posters, carousels, video and copy through the AI providers each workspace configures, and publishes to Instagram, Facebook, LinkedIn, X and YouTube only after a person approves the work.",
    featureList: [
      "Brand knowledge base built from documents, transcripts and reference posts",
      "Per-capability AI provider routing with failover",
      "Human approval gate before any post is published",
      "Multi-channel publishing to Instagram, Facebook, LinkedIn, X and YouTube",
      "Shared engagement inbox with AI-drafted replies",
      "Performance, lead and revenue attribution per post",
      "Workspace-level tenant isolation and audit trails",
    ],
  };
}

export interface FaqEntry {
  question: string;
  answer: string;
}

/**
 * FAQPage markup. The answers must be the same text a reader sees on the page —
 * structured data that does not match the visible content is a manual-action
 * risk, and an answer engine that quotes a hidden answer misrepresents you.
 */
export function faqSchema(entries: readonly FaqEntry[], pagePath: string) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "@id": `${absoluteUrl(pagePath)}#faq`,
    mainEntity: entries.map((entry) => ({
      "@type": "Question",
      name: entry.question,
      acceptedAnswer: { "@type": "Answer", text: entry.answer },
    })),
  };
}

export function breadcrumbSchema(trail: readonly { name: string; path: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: trail.map((crumb, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: crumb.name,
      item: absoluteUrl(crumb.path),
    })),
  };
}

export function webPageSchema(seo: MarketingPageSeo) {
  return {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "@id": `${absoluteUrl(seo.path)}#webpage`,
    url: absoluteUrl(seo.path),
    name: seo.title,
    description: seo.description,
    isPartOf: { "@id": `${SITE_URL}/#organization` },
  };
}
