# Generated by Django 6.1 on 2026-08-20 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('marketing', '0001_initial'),
        ('workspaces', '0002_workspacemember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_format', models.CharField(choices=[('POSTER', 'Poster'), ('CAROUSEL', 'Carousel'), ('VIDEO', 'Video')], default='POSTER', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending review'), ('APPROVED', 'Approved'), ('NEEDS_EDITS', 'Needs edits'), ('REJECTED', 'Rejected'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('headline', models.CharField(blank=True, max_length=500)),
                ('caption', models.TextField(blank=True)),
                ('cta', models.CharField(blank=True, max_length=255)),
                ('hashtags', models.TextField(blank=True)),
                ('preview_url', models.URLField(blank=True, max_length=1000)),
                ('slides', models.JSONField(blank=True, default=list)),
                ('ai_provider', models.CharField(blank=True, max_length=50)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('ai_prompt', models.TextField(blank=True)),
                ('ai_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='marketing.marketingasset')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='brands.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_content', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='content.contentitem')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'content_items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='content_ite_workspa_c9471b_idx'), models.Index(fields=['workspace', '-created_at'], name='content_ite_workspa_fa6a50_idx')],
            },
        ),
    ]
