# Generated by Django 6.1 on 2026-08-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='layout_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='layout_plugin',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
