# Generated by Django 6.1 on 2026-08-10 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('POSTER', 'Poster'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('OTHER_SUPPORTED_ASSET', 'Other Supported Asset')], default='IMAGE', max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('storage_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds for video', null=True)),
                ('source', models.CharField(choices=[('GEMINI_GENERATED', 'Gemini Generated'), ('MANUAL_UPLOAD', 'Manual Upload')], max_length=50)),
                ('generation_id', models.CharField(blank=True, help_text='Reference to GeminiGenerationResult if applicable', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_marketing_assets', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_assets', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'marketing_assets',
            },
        ),
    ]
