# Generated by Django 6.1 on 2026-08-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingasset',
            name='source',
            field=models.CharField(choices=[('GEMINI_GENERATED', 'Gemini Generated'), ('MANUAL_UPLOAD', 'Manual Upload'), ('COMPOSED', 'Composed from brand')], max_length=50),
        ),
    ]
