/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HubRouteImport } from './routes/_hub'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as HubIndexRouteImport } from './routes/_hub.index'
import { Route as HubAccountsRouteImport } from './routes/_hub.accounts'
import { Route as HubAdminRouteImport } from './routes/_hub.admin'
import { Route as HubAnalyticsRouteImport } from './routes/_hub.analytics'
import { Route as HubBrandMasterRouteImport } from './routes/_hub.brand-master'
import { Route as HubOnboardingRouteImport } from './routes/_hub.onboarding'
import { Route as HubPublishingRouteImport } from './routes/_hub.publishing'
import { Route as HubReviewRouteImport } from './routes/_hub.review'
import { Route as HubSettingsRouteImport } from './routes/_hub.settings'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as SocialLinkedinCallbackRouteImport } from './routes/social.linkedin.callback'
import { Route as SocialMetaCallbackRouteImport } from './routes/social.meta.callback'
import { Route as SocialYoutubeCallbackRouteImport } from './routes/social.youtube.callback'

const HubRoute = HubRouteImport.update({
  id: '/_hub',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HubRoute,
} as any)
const HubAccountsRoute = HubAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => HubRoute,
} as any)
const HubAdminRoute = HubAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => HubRoute,
} as any)
const HubAnalyticsRoute = HubAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => HubRoute,
} as any)
const HubBrandMasterRoute = HubBrandMasterRouteImport.update({
  id: '/brand-master',
  path: '/brand-master',
  getParentRoute: () => HubRoute,
} as any)
const HubOnboardingRoute = HubOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => HubRoute,
} as any)
const HubPublishingRoute = HubPublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => HubRoute,
} as any)
const HubReviewRoute = HubReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => HubRoute,
} as any)
const HubSettingsRoute = HubSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HubRoute,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialLinkedinCallbackRoute = SocialLinkedinCallbackRouteImport.update({
  id: '/social/linkedin/callback',
  path: '/social/linkedin/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMetaCallbackRoute = SocialMetaCallbackRouteImport.update({
  id: '/social/meta/callback',
  path: '/social/meta/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialYoutubeCallbackRoute = SocialYoutubeCallbackRouteImport.update({
  id: '/social/youtube/callback',
  path: '/social/youtube/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HubIndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/accounts': typeof HubAccountsRoute
  '/admin': typeof HubAdminRoute
  '/analytics': typeof HubAnalyticsRoute
  '/brand-master': typeof HubBrandMasterRoute
  '/onboarding': typeof HubOnboardingRoute
  '/publishing': typeof HubPublishingRoute
  '/review': typeof HubReviewRoute
  '/settings': typeof HubSettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/social/linkedin/callback': typeof SocialLinkedinCallbackRoute
  '/social/meta/callback': typeof SocialMetaCallbackRoute
  '/social/youtube/callback': typeof SocialYoutubeCallbackRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/accounts': typeof HubAccountsRoute
  '/admin': typeof HubAdminRoute
  '/analytics': typeof HubAnalyticsRoute
  '/brand-master': typeof HubBrandMasterRoute
  '/onboarding': typeof HubOnboardingRoute
  '/publishing': typeof HubPublishingRoute
  '/review': typeof HubReviewRoute
  '/settings': typeof HubSettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/': typeof HubIndexRoute
  '/social/linkedin/callback': typeof SocialLinkedinCallbackRoute
  '/social/meta/callback': typeof SocialMetaCallbackRoute
  '/social/youtube/callback': typeof SocialYoutubeCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_hub': typeof HubRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_hub/accounts': typeof HubAccountsRoute
  '/_hub/admin': typeof HubAdminRoute
  '/_hub/analytics': typeof HubAnalyticsRoute
  '/_hub/brand-master': typeof HubBrandMasterRoute
  '/_hub/onboarding': typeof HubOnboardingRoute
  '/_hub/publishing': typeof HubPublishingRoute
  '/_hub/review': typeof HubReviewRoute
  '/_hub/settings': typeof HubSettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/_hub/': typeof HubIndexRoute
  '/social/linkedin/callback': typeof SocialLinkedinCallbackRoute
  '/social/meta/callback': typeof SocialMetaCallbackRoute
  '/social/youtube/callback': typeof SocialYoutubeCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/accounts'
    | '/admin'
    | '/analytics'
    | '/brand-master'
    | '/onboarding'
    | '/publishing'
    | '/review'
    | '/settings'
    | '/oauth/callback'
    | '/social/linkedin/callback'
    | '/social/meta/callback'
    | '/social/youtube/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/privacy'
    | '/terms'
    | '/accounts'
    | '/admin'
    | '/analytics'
    | '/brand-master'
    | '/onboarding'
    | '/publishing'
    | '/review'
    | '/settings'
    | '/oauth/callback'
    | '/'
    | '/social/linkedin/callback'
    | '/social/meta/callback'
    | '/social/youtube/callback'
  id:
    | '__root__'
    | '/_hub'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_hub/accounts'
    | '/_hub/admin'
    | '/_hub/analytics'
    | '/_hub/brand-master'
    | '/_hub/onboarding'
    | '/_hub/publishing'
    | '/_hub/review'
    | '/_hub/settings'
    | '/oauth/callback'
    | '/_hub/'
    | '/social/linkedin/callback'
    | '/social/meta/callback'
    | '/social/youtube/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HubRoute: typeof HubRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  SocialLinkedinCallbackRoute: typeof SocialLinkedinCallbackRoute
  SocialMetaCallbackRoute: typeof SocialMetaCallbackRoute
  SocialYoutubeCallbackRoute: typeof SocialYoutubeCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_hub': {
      id: '/_hub'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hub/': {
      id: '/_hub/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/accounts': {
      id: '/_hub/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof HubAccountsRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/admin': {
      id: '/_hub/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof HubAdminRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/analytics': {
      id: '/_hub/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof HubAnalyticsRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/brand-master': {
      id: '/_hub/brand-master'
      path: '/brand-master'
      fullPath: '/brand-master'
      preLoaderRoute: typeof HubBrandMasterRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/onboarding': {
      id: '/_hub/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof HubOnboardingRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/publishing': {
      id: '/_hub/publishing'
      path: '/publishing'
      fullPath: '/publishing'
      preLoaderRoute: typeof HubPublishingRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/review': {
      id: '/_hub/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof HubReviewRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/settings': {
      id: '/_hub/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof HubSettingsRouteImport
      parentRoute: typeof HubRoute
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/linkedin/callback': {
      id: '/social/linkedin/callback'
      path: '/social/linkedin/callback'
      fullPath: '/social/linkedin/callback'
      preLoaderRoute: typeof SocialLinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/meta/callback': {
      id: '/social/meta/callback'
      path: '/social/meta/callback'
      fullPath: '/social/meta/callback'
      preLoaderRoute: typeof SocialMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/youtube/callback': {
      id: '/social/youtube/callback'
      path: '/social/youtube/callback'
      fullPath: '/social/youtube/callback'
      preLoaderRoute: typeof SocialYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HubRouteChildren {
  HubAccountsRoute: typeof HubAccountsRoute
  HubAdminRoute: typeof HubAdminRoute
  HubAnalyticsRoute: typeof HubAnalyticsRoute
  HubBrandMasterRoute: typeof HubBrandMasterRoute
  HubOnboardingRoute: typeof HubOnboardingRoute
  HubPublishingRoute: typeof HubPublishingRoute
  HubReviewRoute: typeof HubReviewRoute
  HubSettingsRoute: typeof HubSettingsRoute
  HubIndexRoute: typeof HubIndexRoute
}

const HubRouteChildren: HubRouteChildren = {
  HubAccountsRoute: HubAccountsRoute,
  HubAdminRoute: HubAdminRoute,
  HubAnalyticsRoute: HubAnalyticsRoute,
  HubBrandMasterRoute: HubBrandMasterRoute,
  HubOnboardingRoute: HubOnboardingRoute,
  HubPublishingRoute: HubPublishingRoute,
  HubReviewRoute: HubReviewRoute,
  HubSettingsRoute: HubSettingsRoute,
  HubIndexRoute: HubIndexRoute,
}

const HubRouteWithChildren = HubRoute._addFileChildren(HubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HubRoute: HubRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  SocialLinkedinCallbackRoute: SocialLinkedinCallbackRoute,
  SocialMetaCallbackRoute: SocialMetaCallbackRoute,
  SocialYoutubeCallbackRoute: SocialYoutubeCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
