/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HubRouteImport } from './routes/_hub'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as HubAccountsRouteImport } from './routes/_hub.accounts'
import { Route as HubAdminRouteImport } from './routes/_hub.admin'
import { Route as HubAnalyticsRouteImport } from './routes/_hub.analytics'
import { Route as HubAutopilotRouteImport } from './routes/_hub.autopilot'
import { Route as HubBrandMasterRouteImport } from './routes/_hub.brand-master'
import { Route as HubGrowthRouteImport } from './routes/_hub.growth'
import { Route as HubOnboardingRouteImport } from './routes/_hub.onboarding'
import { Route as HubOverviewRouteImport } from './routes/_hub.overview'
import { Route as HubPublishingRouteImport } from './routes/_hub.publishing'
import { Route as HubReviewRouteImport } from './routes/_hub.review'
import { Route as HubSettingsRouteImport } from './routes/_hub.settings'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as PlatformAdminsRouteImport } from './routes/platform.admins'
import { Route as PlatformClientsRouteImport } from './routes/platform.clients'
import { Route as PlatformLibraryRouteImport } from './routes/platform.library'
import { Route as PlatformPatternsRouteImport } from './routes/platform.patterns'
import { Route as PlatformSignupsRouteImport } from './routes/platform.signups'
import { Route as PlatformStandardsRouteImport } from './routes/platform.standards'
import { Route as PlatformLoginRouteImport } from './routes/platform_.login'
import { Route as PlatformClientsWorkspaceIdRouteImport } from './routes/platform.clients.$workspaceId'
import { Route as SocialLinkedinCallbackRouteImport } from './routes/social.linkedin.callback'
import { Route as SocialMetaCallbackRouteImport } from './routes/social.meta.callback'
import { Route as SocialYoutubeCallbackRouteImport } from './routes/social.youtube.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/_hub',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const HubAccountsRoute = HubAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => HubRoute,
} as any)
const HubAdminRoute = HubAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => HubRoute,
} as any)
const HubAnalyticsRoute = HubAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => HubRoute,
} as any)
const HubAutopilotRoute = HubAutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => HubRoute,
} as any)
const HubBrandMasterRoute = HubBrandMasterRouteImport.update({
  id: '/brand-master',
  path: '/brand-master',
  getParentRoute: () => HubRoute,
} as any)
const HubGrowthRoute = HubGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => HubRoute,
} as any)
const HubOnboardingRoute = HubOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => HubRoute,
} as any)
const HubOverviewRoute = HubOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => HubRoute,
} as any)
const HubPublishingRoute = HubPublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => HubRoute,
} as any)
const HubReviewRoute = HubReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => HubRoute,
} as any)
const HubSettingsRoute = HubSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HubRoute,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAdminsRoute = PlatformAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformClientsRoute = PlatformClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformLibraryRoute = PlatformLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformPatternsRoute = PlatformPatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSignupsRoute = PlatformSignupsRouteImport.update({
  id: '/signups',
  path: '/signups',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformStandardsRoute = PlatformStandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformLoginRoute = PlatformLoginRouteImport.update({
  id: '/platform_/login',
  path: '/platform/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformClientsWorkspaceIdRoute =
  PlatformClientsWorkspaceIdRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => PlatformClientsRoute,
  } as any)
const SocialLinkedinCallbackRoute = SocialLinkedinCallbackRouteImport.update({
  id: '/social/linkedin/callback',
  path: '/social/linkedin/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMetaCallbackRoute = SocialMetaCallbackRouteImport.update({
  id: '/social/meta/callback',
  path: '/social/meta/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialYoutubeCallbackRoute = SocialYoutubeCallbackRouteImport.update({
  id: '/social/youtube/callback',
  path: '/social/youtube/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/accounts': typeof HubAccountsRoute
  '/admin': typeof HubAdminRoute
  '/analytics': typeof HubAnalyticsRoute
  '/autopilot': typeof HubAutopilotRoute
  '/brand-master': typeof HubBrandMasterRoute
  '/growth': typeof HubGrowthRoute
  '/onboarding': typeof HubOnboardingRoute
  '/overview': typeof HubOverviewRoute
  '/publishing': typeof HubPublishingRoute
  '/review': typeof HubReviewRoute
  '/settings': typeof HubSettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/platform/admins': typeof PlatformAdminsRoute
  '/platform/clients': typeof PlatformClientsRouteWithChildren
  '/platform/library': typeof PlatformLibraryRoute
  '/platform/patterns': typeof PlatformPatternsRoute
  '/platform/signups': typeof PlatformSignupsRoute
  '/platform/standards': typeof PlatformStandardsRoute
  '/platform/login': typeof PlatformLoginRoute
  '/platform/': typeof PlatformIndexRoute
  '/platform/clients/$workspaceId': typeof PlatformClientsWorkspaceIdRoute
  '/social/linkedin/callback': typeof SocialLinkedinCallbackRoute
  '/social/meta/callback': typeof SocialMetaCallbackRoute
  '/social/youtube/callback': typeof SocialYoutubeCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/accounts': typeof HubAccountsRoute
  '/admin': typeof HubAdminRoute
  '/analytics': typeof HubAnalyticsRoute
  '/autopilot': typeof HubAutopilotRoute
  '/brand-master': typeof HubBrandMasterRoute
  '/growth': typeof HubGrowthRoute
  '/onboarding': typeof HubOnboardingRoute
  '/overview': typeof HubOverviewRoute
  '/publishing': typeof HubPublishingRoute
  '/review': typeof HubReviewRoute
  '/settings': typeof HubSettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/platform/admins': typeof PlatformAdminsRoute
  '/platform/clients': typeof PlatformClientsRouteWithChildren
  '/platform/library': typeof PlatformLibraryRoute
  '/platform/patterns': typeof PlatformPatternsRoute
  '/platform/signups': typeof PlatformSignupsRoute
  '/platform/standards': typeof PlatformStandardsRoute
  '/platform/login': typeof PlatformLoginRoute
  '/platform': typeof PlatformIndexRoute
  '/platform/clients/$workspaceId': typeof PlatformClientsWorkspaceIdRoute
  '/social/linkedin/callback': typeof SocialLinkedinCallbackRoute
  '/social/meta/callback': typeof SocialMetaCallbackRoute
  '/social/youtube/callback': typeof SocialYoutubeCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_hub': typeof HubRouteWithChildren
  '/capabilities': typeof CapabilitiesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/_hub/accounts': typeof HubAccountsRoute
  '/_hub/admin': typeof HubAdminRoute
  '/_hub/analytics': typeof HubAnalyticsRoute
  '/_hub/autopilot': typeof HubAutopilotRoute
  '/_hub/brand-master': typeof HubBrandMasterRoute
  '/_hub/growth': typeof HubGrowthRoute
  '/_hub/onboarding': typeof HubOnboardingRoute
  '/_hub/overview': typeof HubOverviewRoute
  '/_hub/publishing': typeof HubPublishingRoute
  '/_hub/review': typeof HubReviewRoute
  '/_hub/settings': typeof HubSettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/platform/admins': typeof PlatformAdminsRoute
  '/platform/clients': typeof PlatformClientsRouteWithChildren
  '/platform/library': typeof PlatformLibraryRoute
  '/platform/patterns': typeof PlatformPatternsRoute
  '/platform/signups': typeof PlatformSignupsRoute
  '/platform/standards': typeof PlatformStandardsRoute
  '/platform_/login': typeof PlatformLoginRoute
  '/platform/': typeof PlatformIndexRoute
  '/platform/clients/$workspaceId': typeof PlatformClientsWorkspaceIdRoute
  '/social/linkedin/callback': typeof SocialLinkedinCallbackRoute
  '/social/meta/callback': typeof SocialMetaCallbackRoute
  '/social/youtube/callback': typeof SocialYoutubeCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capabilities'
    | '/how-it-works'
    | '/login'
    | '/platform'
    | '/privacy'
    | '/setup'
    | '/signup'
    | '/terms'
    | '/trust'
    | '/accounts'
    | '/admin'
    | '/analytics'
    | '/autopilot'
    | '/brand-master'
    | '/growth'
    | '/onboarding'
    | '/overview'
    | '/publishing'
    | '/review'
    | '/settings'
    | '/oauth/callback'
    | '/platform/admins'
    | '/platform/clients'
    | '/platform/library'
    | '/platform/patterns'
    | '/platform/signups'
    | '/platform/standards'
    | '/platform/login'
    | '/platform/'
    | '/platform/clients/$workspaceId'
    | '/social/linkedin/callback'
    | '/social/meta/callback'
    | '/social/youtube/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capabilities'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/setup'
    | '/signup'
    | '/terms'
    | '/trust'
    | '/accounts'
    | '/admin'
    | '/analytics'
    | '/autopilot'
    | '/brand-master'
    | '/growth'
    | '/onboarding'
    | '/overview'
    | '/publishing'
    | '/review'
    | '/settings'
    | '/oauth/callback'
    | '/platform/admins'
    | '/platform/clients'
    | '/platform/library'
    | '/platform/patterns'
    | '/platform/signups'
    | '/platform/standards'
    | '/platform/login'
    | '/platform'
    | '/platform/clients/$workspaceId'
    | '/social/linkedin/callback'
    | '/social/meta/callback'
    | '/social/youtube/callback'
  id:
    | '__root__'
    | '/'
    | '/_hub'
    | '/capabilities'
    | '/how-it-works'
    | '/login'
    | '/platform'
    | '/privacy'
    | '/setup'
    | '/signup'
    | '/terms'
    | '/trust'
    | '/_hub/accounts'
    | '/_hub/admin'
    | '/_hub/analytics'
    | '/_hub/autopilot'
    | '/_hub/brand-master'
    | '/_hub/growth'
    | '/_hub/onboarding'
    | '/_hub/overview'
    | '/_hub/publishing'
    | '/_hub/review'
    | '/_hub/settings'
    | '/oauth/callback'
    | '/platform/admins'
    | '/platform/clients'
    | '/platform/library'
    | '/platform/patterns'
    | '/platform/signups'
    | '/platform/standards'
    | '/platform_/login'
    | '/platform/'
    | '/platform/clients/$workspaceId'
    | '/social/linkedin/callback'
    | '/social/meta/callback'
    | '/social/youtube/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HubRoute: typeof HubRouteWithChildren
  CapabilitiesRoute: typeof CapabilitiesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  PlatformLoginRoute: typeof PlatformLoginRoute
  SocialLinkedinCallbackRoute: typeof SocialLinkedinCallbackRoute
  SocialMetaCallbackRoute: typeof SocialMetaCallbackRoute
  SocialYoutubeCallbackRoute: typeof SocialYoutubeCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hub': {
      id: '/_hub'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hub/accounts': {
      id: '/_hub/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof HubAccountsRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/admin': {
      id: '/_hub/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof HubAdminRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/analytics': {
      id: '/_hub/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof HubAnalyticsRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/autopilot': {
      id: '/_hub/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof HubAutopilotRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/brand-master': {
      id: '/_hub/brand-master'
      path: '/brand-master'
      fullPath: '/brand-master'
      preLoaderRoute: typeof HubBrandMasterRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/growth': {
      id: '/_hub/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof HubGrowthRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/onboarding': {
      id: '/_hub/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof HubOnboardingRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/overview': {
      id: '/_hub/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof HubOverviewRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/publishing': {
      id: '/_hub/publishing'
      path: '/publishing'
      fullPath: '/publishing'
      preLoaderRoute: typeof HubPublishingRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/review': {
      id: '/_hub/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof HubReviewRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/settings': {
      id: '/_hub/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof HubSettingsRouteImport
      parentRoute: typeof HubRoute
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/admins': {
      id: '/platform/admins'
      path: '/admins'
      fullPath: '/platform/admins'
      preLoaderRoute: typeof PlatformAdminsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/clients': {
      id: '/platform/clients'
      path: '/clients'
      fullPath: '/platform/clients'
      preLoaderRoute: typeof PlatformClientsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/library': {
      id: '/platform/library'
      path: '/library'
      fullPath: '/platform/library'
      preLoaderRoute: typeof PlatformLibraryRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/patterns': {
      id: '/platform/patterns'
      path: '/patterns'
      fullPath: '/platform/patterns'
      preLoaderRoute: typeof PlatformPatternsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/signups': {
      id: '/platform/signups'
      path: '/signups'
      fullPath: '/platform/signups'
      preLoaderRoute: typeof PlatformSignupsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/standards': {
      id: '/platform/standards'
      path: '/standards'
      fullPath: '/platform/standards'
      preLoaderRoute: typeof PlatformStandardsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform_/login': {
      id: '/platform_/login'
      path: '/platform/login'
      fullPath: '/platform/login'
      preLoaderRoute: typeof PlatformLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/clients/$workspaceId': {
      id: '/platform/clients/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/platform/clients/$workspaceId'
      preLoaderRoute: typeof PlatformClientsWorkspaceIdRouteImport
      parentRoute: typeof PlatformClientsRoute
    }
    '/social/linkedin/callback': {
      id: '/social/linkedin/callback'
      path: '/social/linkedin/callback'
      fullPath: '/social/linkedin/callback'
      preLoaderRoute: typeof SocialLinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/meta/callback': {
      id: '/social/meta/callback'
      path: '/social/meta/callback'
      fullPath: '/social/meta/callback'
      preLoaderRoute: typeof SocialMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/youtube/callback': {
      id: '/social/youtube/callback'
      path: '/social/youtube/callback'
      fullPath: '/social/youtube/callback'
      preLoaderRoute: typeof SocialYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HubRouteChildren {
  HubAccountsRoute: typeof HubAccountsRoute
  HubAdminRoute: typeof HubAdminRoute
  HubAnalyticsRoute: typeof HubAnalyticsRoute
  HubAutopilotRoute: typeof HubAutopilotRoute
  HubBrandMasterRoute: typeof HubBrandMasterRoute
  HubGrowthRoute: typeof HubGrowthRoute
  HubOnboardingRoute: typeof HubOnboardingRoute
  HubOverviewRoute: typeof HubOverviewRoute
  HubPublishingRoute: typeof HubPublishingRoute
  HubReviewRoute: typeof HubReviewRoute
  HubSettingsRoute: typeof HubSettingsRoute
}

const HubRouteChildren: HubRouteChildren = {
  HubAccountsRoute: HubAccountsRoute,
  HubAdminRoute: HubAdminRoute,
  HubAnalyticsRoute: HubAnalyticsRoute,
  HubAutopilotRoute: HubAutopilotRoute,
  HubBrandMasterRoute: HubBrandMasterRoute,
  HubGrowthRoute: HubGrowthRoute,
  HubOnboardingRoute: HubOnboardingRoute,
  HubOverviewRoute: HubOverviewRoute,
  HubPublishingRoute: HubPublishingRoute,
  HubReviewRoute: HubReviewRoute,
  HubSettingsRoute: HubSettingsRoute,
}

const HubRouteWithChildren = HubRoute._addFileChildren(HubRouteChildren)

interface PlatformClientsRouteChildren {
  PlatformClientsWorkspaceIdRoute: typeof PlatformClientsWorkspaceIdRoute
}

const PlatformClientsRouteChildren: PlatformClientsRouteChildren = {
  PlatformClientsWorkspaceIdRoute: PlatformClientsWorkspaceIdRoute,
}

const PlatformClientsRouteWithChildren = PlatformClientsRoute._addFileChildren(
  PlatformClientsRouteChildren,
)

interface PlatformRouteChildren {
  PlatformAdminsRoute: typeof PlatformAdminsRoute
  PlatformClientsRoute: typeof PlatformClientsRouteWithChildren
  PlatformLibraryRoute: typeof PlatformLibraryRoute
  PlatformPatternsRoute: typeof PlatformPatternsRoute
  PlatformSignupsRoute: typeof PlatformSignupsRoute
  PlatformStandardsRoute: typeof PlatformStandardsRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformAdminsRoute: PlatformAdminsRoute,
  PlatformClientsRoute: PlatformClientsRouteWithChildren,
  PlatformLibraryRoute: PlatformLibraryRoute,
  PlatformPatternsRoute: PlatformPatternsRoute,
  PlatformSignupsRoute: PlatformSignupsRoute,
  PlatformStandardsRoute: PlatformStandardsRoute,
  PlatformIndexRoute: PlatformIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HubRoute: HubRouteWithChildren,
  CapabilitiesRoute: CapabilitiesRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PlatformRoute: PlatformRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  PlatformLoginRoute: PlatformLoginRoute,
  SocialLinkedinCallbackRoute: SocialLinkedinCallbackRoute,
  SocialMetaCallbackRoute: SocialMetaCallbackRoute,
  SocialYoutubeCallbackRoute: SocialYoutubeCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
