/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HubRouteImport } from './routes/_hub'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as HubIndexRouteImport } from './routes/_hub.index'
import { Route as HubAccountsRouteImport } from './routes/_hub.accounts'
import { Route as HubAnalyticsRouteImport } from './routes/_hub.analytics'
import { Route as HubPublishingRouteImport } from './routes/_hub.publishing'
import { Route as HubSettingsRouteImport } from './routes/_hub.settings'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as SocialLinkedinCallbackRouteImport } from './routes/social.linkedin.callback'

const HubRoute = HubRouteImport.update({
  id: '/_hub',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HubRoute,
} as any)
const HubAccountsRoute = HubAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => HubRoute,
} as any)
const HubAnalyticsRoute = HubAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => HubRoute,
} as any)
const HubPublishingRoute = HubPublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => HubRoute,
} as any)
const HubSettingsRoute = HubSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HubRoute,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialLinkedinCallbackRoute = SocialLinkedinCallbackRouteImport.update({
  id: '/social/linkedin/callback',
  path: '/social/linkedin/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HubIndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/accounts': typeof HubAccountsRoute
  '/analytics': typeof HubAnalyticsRoute
  '/publishing': typeof HubPublishingRoute
  '/settings': typeof HubSettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/social/linkedin/callback': typeof SocialLinkedinCallbackRoute
}
export interface FileRoutesByTo {
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/accounts': typeof HubAccountsRoute
  '/analytics': typeof HubAnalyticsRoute
  '/publishing': typeof HubPublishingRoute
  '/settings': typeof HubSettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/': typeof HubIndexRoute
  '/social/linkedin/callback': typeof SocialLinkedinCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_hub': typeof HubRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_hub/accounts': typeof HubAccountsRoute
  '/_hub/analytics': typeof HubAnalyticsRoute
  '/_hub/publishing': typeof HubPublishingRoute
  '/_hub/settings': typeof HubSettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/_hub/': typeof HubIndexRoute
  '/social/linkedin/callback': typeof SocialLinkedinCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/accounts'
    | '/analytics'
    | '/publishing'
    | '/settings'
    | '/oauth/callback'
    | '/social/linkedin/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/privacy'
    | '/terms'
    | '/accounts'
    | '/analytics'
    | '/publishing'
    | '/settings'
    | '/oauth/callback'
    | '/'
    | '/social/linkedin/callback'
  id:
    | '__root__'
    | '/_hub'
    | '/privacy'
    | '/terms'
    | '/_hub/accounts'
    | '/_hub/analytics'
    | '/_hub/publishing'
    | '/_hub/settings'
    | '/oauth/callback'
    | '/_hub/'
    | '/social/linkedin/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HubRoute: typeof HubRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  SocialLinkedinCallbackRoute: typeof SocialLinkedinCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_hub': {
      id: '/_hub'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hub/': {
      id: '/_hub/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/accounts': {
      id: '/_hub/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof HubAccountsRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/analytics': {
      id: '/_hub/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof HubAnalyticsRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/publishing': {
      id: '/_hub/publishing'
      path: '/publishing'
      fullPath: '/publishing'
      preLoaderRoute: typeof HubPublishingRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/settings': {
      id: '/_hub/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof HubSettingsRouteImport
      parentRoute: typeof HubRoute
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/linkedin/callback': {
      id: '/social/linkedin/callback'
      path: '/social/linkedin/callback'
      fullPath: '/social/linkedin/callback'
      preLoaderRoute: typeof SocialLinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HubRouteChildren {
  HubAccountsRoute: typeof HubAccountsRoute
  HubAnalyticsRoute: typeof HubAnalyticsRoute
  HubPublishingRoute: typeof HubPublishingRoute
  HubSettingsRoute: typeof HubSettingsRoute
  HubIndexRoute: typeof HubIndexRoute
}

const HubRouteChildren: HubRouteChildren = {
  HubAccountsRoute: HubAccountsRoute,
  HubAnalyticsRoute: HubAnalyticsRoute,
  HubPublishingRoute: HubPublishingRoute,
  HubSettingsRoute: HubSettingsRoute,
  HubIndexRoute: HubIndexRoute,
}

const HubRouteWithChildren = HubRoute._addFileChildren(HubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HubRoute: HubRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  SocialLinkedinCallbackRoute: SocialLinkedinCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
