# Generated by Django 6.1 on 2026-08-21 12:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('workspaces', '0002_workspacemember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=64)),
                ('attribute', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True)),
                ('weight', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('confidence', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('EMERGING', 'Emerging'), ('ESTABLISHED', 'Established'), ('RETIRED', 'Retired')], default='EMERGING', max_length=16)),
                ('scope', models.CharField(choices=[('ASSET', 'This asset only'), ('CAMPAIGN', 'This campaign'), ('BRAND', 'The whole brand'), ('TENANT', 'Every brand in the workspace')], default='BRAND', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='brands.brand')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'learning_brand_preferences',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['brand', 'category', 'attribute'], name='learning_br_brand_i_1537c1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'RETIRED'), _negated=True), fields=('workspace', 'brand', 'category', 'attribute'), name='uniq_active_brand_preference')],
            },
        ),
        migrations.CreateModel(
            name='BrandRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('structured', models.JSONField(blank=True, default=dict)),
                ('hardness', models.CharField(choices=[('SOFT', 'Preference the generator should follow'), ('HARD', 'Constraint the generator must not break')], default='SOFT', max_length=8)),
                ('origin', models.CharField(choices=[('EXPLICIT', 'Stated by a user'), ('LEARNED', 'Inferred from evidence')], default='EXPLICIT', max_length=16)),
                ('priority', models.IntegerField(default=0)),
                ('scope', models.CharField(choices=[('ASSET', 'This asset only'), ('CAMPAIGN', 'This campaign'), ('BRAND', 'The whole brand'), ('TENANT', 'Every brand in the workspace')], default='BRAND', max_length=16)),
                ('evidence_event_ids', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='brands.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_rules_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_brand_rules', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'learning_brand_rules',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['brand', 'is_active'], name='learning_br_brand_i_d5bb7f_idx'), models.Index(fields=['workspace', 'hardness'], name='learning_br_workspa_aaea6d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('hardness', 'HARD'), ('origin', 'LEARNED'), _negated=True), name='learned_rules_are_never_hard')],
            },
        ),
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('APPROVED', 'Approved'), ('EDITED', 'Edited'), ('REJECTED', 'Rejected'), ('REDO', 'Redo requested'), ('EXPLICIT_RULE', 'Explicit instruction'), ('PREFERENCE_SIGNAL', 'Preference signal'), ('INSPIRATION_SIGNAL', 'Inspiration signal'), ('PUBLISHED', 'Published'), ('PERFORMANCE_OBSERVED', 'Performance observed'), ('MEMORY_CONFIRMED', 'Memory confirmed'), ('MEMORY_REJECTED', 'Memory rejected')], max_length=32)),
                ('outcome', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('MIXED', 'Mixed')], default='NEUTRAL', max_length=16)),
                ('subject_type', models.CharField(choices=[('CONTENT_ITEM', 'Content item'), ('FEEDBACK', 'Feedback'), ('BRAND', 'Brand'), ('BRAND_SOURCE', 'Knowledge source'), ('BRAND_MEMORY', 'Brand memory'), ('INSPIRATION', 'Inspiration'), ('INSPIRATION_SIGNAL', 'Inspiration signal'), ('PUBLISHING_JOB', 'Publishing job'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('subject_id', models.UUIDField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, choices=[('CONTENT_ITEM', 'Content item'), ('FEEDBACK', 'Feedback'), ('BRAND', 'Brand'), ('BRAND_SOURCE', 'Knowledge source'), ('BRAND_MEMORY', 'Brand memory'), ('INSPIRATION', 'Inspiration'), ('INSPIRATION_SIGNAL', 'Inspiration signal'), ('PUBLISHING_JOB', 'Publishing job'), ('OTHER', 'Other')], default='', max_length=32)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('eligibility_for_aggregate_learning', models.BooleanField(default=False)),
                ('dedupe_key', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='brands.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'learning_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='learning_ev_workspa_6eb165_idx'), models.Index(fields=['brand', 'event_type'], name='learning_ev_brand_i_3454c1_idx'), models.Index(fields=['subject_type', 'subject_id'], name='learning_ev_subject_061515_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('workspace', 'dedupe_key'), name='uniq_learning_event_dedupe_key')],
            },
        ),
    ]
