# Generated by Django 6.1 on 2026-08-21 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def repair_scope_and_evidence(apps, schema_editor):
    """Make existing rows satisfy the rules the constraints below enforce.

    0001 shipped without them, so a database that ran it can legally hold
    exactly what 0002 refuses: a brandless BRAND-scoped rule, a TENANT-scoped
    row pinned to a brand, several live workspace-wide preferences for one
    attribute. AddConstraint on such a table aborts the whole migration and
    leaves the code deployed against a schema that lacks the new columns.

    Nothing is deleted. Rows are moved to the scope they actually have, and
    duplicates are retired rather than removed.
    """
    BrandRule = apps.get_model('learning', 'BrandRule')
    BrandPreference = apps.get_model('learning', 'BrandPreference')

    for model in (BrandRule, BrandPreference):
        # A row with no brand is workspace-wide whatever it claimed.
        model.objects.filter(brand__isnull=True).exclude(scope='TENANT').update(
            scope='TENANT'
        )
        # A row naming a brand is not workspace-wide.
        model.objects.filter(brand__isnull=False, scope='TENANT').update(scope='BRAND')

    # Only one live workspace-wide preference per attribute; keep the newest.
    seen = set()
    for preference in (
        BrandPreference.objects.filter(brand__isnull=True)
        .exclude(state='RETIRED')
        .order_by('-updated_at', '-id')
        .iterator()
    ):
        key = (preference.workspace_id, preference.category, preference.attribute)
        if key in seen:
            preference.state = 'RETIRED'
            preference.save(update_fields=['state'])
        else:
            seen.add(key)

    # evidence_count predates the lineage table, so nothing stands behind it.
    # Reporting ESTABLISHED on evidence that cannot be named is the fake state
    # the rules forbid; these fall back to EMERGING and re-earn it.
    BrandPreference.objects.all().update(evidence_count=0, state='EMERGING')


def refuse_reverse(apps, schema_editor):
    from django.db.migrations.exceptions import IrreversibleError

    raise IrreversibleError(
        "0002_preference_evidence cannot be reversed: it retired duplicate "
        "workspace-wide preferences and reset unbacked evidence counts, and "
        "0001 has no column to restore them to."
    )


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('learning', '0001_initial'),
        ('workspaces', '0002_workspacemember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_preference_evidence',
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(repair_scope_and_evidence, refuse_reverse),
        migrations.AddConstraint(
            model_name='brandpreference',
            constraint=models.UniqueConstraint(condition=models.Q(('brand__isnull', True), models.Q(('state', 'RETIRED'), _negated=True)), fields=('workspace', 'category', 'attribute'), name='uniq_active_tenant_preference'),
        ),
        migrations.AddConstraint(
            model_name='brandpreference',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('brand__isnull', True), ('scope', 'TENANT')), models.Q(models.Q(('scope', 'TENANT'), _negated=True), ('brand__isnull', False)), _connector='OR'), name='brand_preference_scope_matches_brand'),
        ),
        migrations.AddConstraint(
            model_name='brandrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('brand__isnull', True), ('scope', 'TENANT')), models.Q(models.Q(('scope', 'TENANT'), _negated=True), ('brand__isnull', False)), _connector='OR'), name='brand_rule_scope_matches_brand'),
        ),
        migrations.AddField(
            model_name='preferenceevidence',
            name='learning_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_evidence', to='learning.learningevent'),
        ),
        migrations.AddField(
            model_name='preferenceevidence',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='learning.brandpreference'),
        ),
        migrations.AddConstraint(
            model_name='preferenceevidence',
            constraint=models.UniqueConstraint(fields=('preference', 'learning_event'), name='uniq_preference_evidence'),
        ),
    ]
