# Generated by Django 6.1 on 2026-08-21 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('learning', '0001_initial'),
        ('workspaces', '0002_workspacemember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_preference_evidence',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='brandpreference',
            constraint=models.UniqueConstraint(condition=models.Q(('brand__isnull', True), models.Q(('state', 'RETIRED'), _negated=True)), fields=('workspace', 'category', 'attribute'), name='uniq_active_tenant_preference'),
        ),
        migrations.AddConstraint(
            model_name='brandpreference',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('brand__isnull', True), ('scope', 'TENANT')), models.Q(models.Q(('scope', 'TENANT'), _negated=True), ('brand__isnull', False)), _connector='OR'), name='brand_preference_scope_matches_brand'),
        ),
        migrations.AddConstraint(
            model_name='brandrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('brand__isnull', True), ('scope', 'TENANT')), models.Q(models.Q(('scope', 'TENANT'), _negated=True), ('brand__isnull', False)), _connector='OR'), name='brand_rule_scope_matches_brand'),
        ),
        migrations.AddField(
            model_name='preferenceevidence',
            name='learning_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_evidence', to='learning.learningevent'),
        ),
        migrations.AddField(
            model_name='preferenceevidence',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='learning.brandpreference'),
        ),
        migrations.AddConstraint(
            model_name='preferenceevidence',
            constraint=models.UniqueConstraint(fields=('preference', 'learning_event'), name='uniq_preference_evidence'),
        ),
    ]
