# Generated by Django 6.1 on 2026-08-10 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
        ('social_accounts', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('QUEUED', 'Queued'), ('PUBLISHING', 'Publishing'), ('PARTIALLY_PUBLISHED', 'Partially Published'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=50)),
                ('publish_mode', models.CharField(choices=[('NOW', 'Now'), ('SCHEDULED', 'Scheduled')], default='NOW', max_length=50)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishing_jobs', to='marketing.marketingasset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_publishing_jobs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishing_jobs', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'publishing_jobs',
            },
        ),
        migrations.CreateModel(
            name='PublishingJobItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PUBLISHING', 'Publishing'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=50)),
                ('external_post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_post_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('publishing_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='publishing.publishingjob')),
                ('social_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishing_job_items', to='social_accounts.socialconnection')),
            ],
            options={
                'db_table': 'publishing_job_items',
                'unique_together': {('publishing_job', 'social_connection')},
            },
        ),
    ]
