# Generated by Django 6.1 on 2026-08-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishingjob',
            name='caption',
            field=models.TextField(blank=True, default='', help_text='Post caption/text to publish'),
        ),
    ]
