# Generated by Django 6.1 on 2026-08-10 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiGenerationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_data', models.TextField(blank=True, help_text='Raw prompt or structure sent to Gemini', null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('target_audience', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('occasion', models.CharField(blank=True, max_length=255, null=True)),
                ('offer', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_tone', models.CharField(blank=True, max_length=255, null=True)),
                ('content_format', models.CharField(blank=True, max_length=255, null=True)),
                ('visual_direction', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('provider', models.CharField(default='GOOGLE_GEMINI', editable=False, max_length=50)),
                ('model', models.CharField(default='gemini-1.5-pro', max_length=100)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gemini_requests', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'gemini_generation_requests',
            },
        ),
        migrations.CreateModel(
            name='GeminiGenerationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_text', models.TextField(blank=True, null=True)),
                ('generated_asset_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemini_results', to='marketing.marketingasset')),
                ('generation_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='gemini.geminigenerationrequest')),
            ],
            options={
                'db_table': 'gemini_generation_results',
            },
        ),
    ]
