# Generated by Django 6.1 on 2026-09-01 11:11

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0004_brand_brain_health'),
        ('content', '0002_contentitem_layout_config_contentitem_layout_plugin'),
        ('gemini', '0002_provider_neutral_request_defaults'),
        ('publishing', '0003_publishingjob_content_item'),
        ('social_accounts', '0001_initial'),
        ('workspaces', '0005_workspace_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutopilotPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('objective', models.TextField()),
                ('campaign_brief', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('ASSISTED', 'Draft only'), ('APPROVAL_REQUIRED', 'Human approval required')], default='APPROVAL_REQUIRED', max_length=24)),
                ('cadence', models.CharField(choices=[('MANUAL', 'Manual only')], default='MANUAL', max_length=16)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_formats', models.JSONField(blank=True, default=list)),
                ('daily_generation_limit', models.PositiveIntegerField(default=1)),
                ('monthly_spend_cap', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='0 means the workspace billing cap is the only spend cap.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('enabled', models.BooleanField(default=False)),
                ('paused', models.BooleanField(default=False)),
                ('emergency_stop', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autopilot_policies', to='brands.brand')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopilot_policies_created', to=settings.AUTH_USER_MODEL)),
                ('social_connections', models.ManyToManyField(blank=True, related_name='autopilot_policies', to='social_accounts.socialconnection')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autopilot_policies', to='workspaces.marketingworkspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutopilotRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('WAITING_GENERATION', 'Waiting for generation'), ('WAITING_REVIEW', 'Waiting for human review'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], default='QUEUED', max_length=28)),
                ('scheduled_for', models.DateTimeField()),
                ('dedupe_key', models.CharField(max_length=255)),
                ('policy_snapshot', models.JSONField(default=dict)),
                ('task_id', models.CharField(blank=True, max_length=64)),
                ('next_check_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopilot_runs', to='content.contentitem')),
                ('generation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopilot_runs', to='gemini.geminigenerationrequest')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopilot_runs_initiated', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='autopilot.autopilotpolicy')),
                ('publishing_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopilot_runs', to='publishing.publishingjob')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autopilot_runs', to='workspaces.marketingworkspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutopilotStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=24)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='autopilot.autopilotrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='autopilotpolicy',
            index=models.Index(fields=['workspace', 'enabled', 'paused'], name='autopilot_a_workspa_fb9bc3_idx'),
        ),
        migrations.AddIndex(
            model_name='autopilotpolicy',
            index=models.Index(fields=['enabled', 'next_run_at'], name='autopilot_a_enabled_aba534_idx'),
        ),
        migrations.AddConstraint(
            model_name='autopilotpolicy',
            constraint=models.UniqueConstraint(fields=('workspace', 'brand', 'name'), name='uniq_autopilot_policy_name'),
        ),
        migrations.AddConstraint(
            model_name='autopilotpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_spend_cap__gte', 0)), name='autopilot_spend_cap_non_negative'),
        ),
        migrations.AddIndex(
            model_name='autopilotrun',
            index=models.Index(fields=['workspace', 'status', '-created_at'], name='autopilot_a_workspa_35c838_idx'),
        ),
        migrations.AddIndex(
            model_name='autopilotrun',
            index=models.Index(fields=['status', 'next_check_at'], name='autopilot_a_status_58ab59_idx'),
        ),
        migrations.AddConstraint(
            model_name='autopilotrun',
            constraint=models.UniqueConstraint(fields=('workspace', 'dedupe_key'), name='uniq_autopilot_run_dedupe'),
        ),
        migrations.AddConstraint(
            model_name='autopilotstep',
            constraint=models.UniqueConstraint(fields=('run', 'key'), name='uniq_autopilot_run_step'),
        ),
    ]
