# Generated by Django 6.1 on 2026-09-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopilot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopilotpolicy',
            name='cadence',
            field=models.CharField(choices=[('MANUAL', 'Manual only'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='MANUAL', max_length=16),
        ),
    ]
