# Generated by Django 6.1 on 2026-08-23 02:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_client_code_and_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUniversalSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('standards_enabled', models.BooleanField(default=True)),
                ('inspirations_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='universal_settings', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'client_universal_settings',
            },
        ),
        migrations.CreateModel(
            name='PlatformInspiration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('reference_url', models.URLField(max_length=1000)),
                ('annotation', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('channel', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_inspirations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_inspirations',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'industry'], name='platform_in_status_84524f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UniversalStandard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('rationale', models.TextField(blank=True)),
                ('category', models.CharField(max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=255)),
                ('guidance', models.TextField()),
                ('scope', models.CharField(choices=[('GLOBAL', 'Every client'), ('INDUSTRY', 'One industry'), ('CHANNEL', 'One channel'), ('CONTENT_TYPE', 'One content type')], default='GLOBAL', max_length=20)),
                ('scope_value', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_standards', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='universal.universalstandard')),
            ],
            options={
                'db_table': 'universal_standards',
                'ordering': ['category', 'attribute', 'title'],
                'indexes': [models.Index(fields=['status', 'scope'], name='universal_s_status_0ae13c_idx'), models.Index(fields=['category', 'attribute'], name='universal_s_categor_706b16_idx')],
            },
        ),
    ]
