# Generated by Django 6.1 on 2026-08-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforminspiration',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='platforminspiration',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='platforminspiration',
            name='file_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='platforminspiration',
            name='kind',
            field=models.CharField(choices=[('LINK', 'Link'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('FILE', 'File'), ('TEXT', 'Text')], default='LINK', max_length=10),
        ),
        migrations.AddField(
            model_name='platforminspiration',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='platforminspiration',
            name='storage_path',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='platforminspiration',
            name='reference_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
