# Generated by Django 6.1 on 2026-09-04 04:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal', '0003_learned_pattern'),
        ('workspaces', '0005_workspace_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientQualitySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('critique_enabled', models.BooleanField(default=True)),
                ('focus_crop_enabled', models.BooleanField(default=True)),
                ('variety_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_settings', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'client_quality_settings',
            },
        ),
    ]
