# Generated by Django 6.1 on 2026-09-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal', '0004_clientqualitysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientqualitysettings',
            name='image_text_check_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
