# Generated by Django 6.1 on 2026-08-20 12:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('content', '0001_initial'),
        ('marketing', '0001_initial'),
        ('workspaces', '0002_workspacemember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('group', models.CharField(choices=[('TYPOGRAPHY', 'Typography'), ('COPY', 'Copy & message'), ('LINE_BY_LINE', 'Line-by-line'), ('LOGO', 'Logo & branding'), ('VISUAL', 'Visual & background'), ('LAYOUT', 'Layout'), ('AUDIO', 'Audio'), ('FORMAT', 'Format & technical'), ('STRATEGY', 'Strategy')], max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_provisional', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'feedback_elements',
                'ordering': ['group', 'position', 'label'],
                'indexes': [models.Index(fields=['group', 'position'], name='feedback_el_group_ed77ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verdict', models.CharField(choices=[('APPROVE', 'Approve'), ('NEEDS_EDITS', 'Needs edits'), ('REJECT', 'Reject')], max_length=20)),
                ('element_keys', models.JSONField(blank=True, default=list)),
                ('feedback_text', models.TextField(blank=True)),
                ('fix_request', models.TextField(blank=True)),
                ('sentiment', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative')], default='NEUTRAL', max_length=20)),
                ('urgency', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High')], default='NORMAL', max_length=20)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('embedding_model', models.CharField(blank=True, max_length=100)),
                ('pattern_extracted', models.JSONField(blank=True, default=dict)),
                ('rules_updated', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('after_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_after', to='marketing.marketingasset')),
                ('before_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_before', to='marketing.marketingasset')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='brands.brand')),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='content.contentitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_feedback', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='feedback_workspa_790358_idx'), models.Index(fields=['workspace', 'verdict'], name='feedback_workspa_cc0c62_idx')],
            },
        ),
    ]
