# Generated by Django 6.1 on 2026-08-10 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn'), ('X', 'X'), ('TIKTOK', 'TikTok'), ('YOUTUBE', 'YouTube'), ('GOOGLE_BUSINESS', 'Google Business Profile')], max_length=50)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('external_account_id', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('profile_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('connected_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('connected_user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('connected_user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_role', models.CharField(blank=True, max_length=50, null=True)),
                ('oauth_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('oauth_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token_encrypted', models.TextField(blank=True, null=True)),
                ('refresh_token_encrypted', models.TextField(blank=True, null=True)),
                ('token_created_at', models.DateTimeField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_token_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_CONNECTED', 'Not Connected'), ('CONNECTING', 'Connecting'), ('CONNECTED', 'Connected'), ('PERMISSION_MISSING', 'Permission Missing'), ('TOKEN_EXPIRED', 'Token Expired'), ('REAUTHORIZATION_REQUIRED', 'Reauthorization Required'), ('REVOKED', 'Revoked'), ('CONNECTION_FAILED', 'Connection Failed'), ('PUBLISHING_DISABLED', 'Publishing Disabled'), ('DISCONNECTED', 'Disconnected'), ('PLATFORM_UNAVAILABLE', 'Platform Unavailable')], default='NOT_CONNECTED', max_length=50)),
                ('publishing_enabled', models.BooleanField(default=True)),
                ('is_default_account', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('reauthorization_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_social_accounts', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_connections', to='workspaces.marketingworkspace')),
            ],
            options={
                'db_table': 'social_connections',
                'unique_together': {('workspace', 'platform', 'external_account_id')},
            },
        ),
        migrations.CreateModel(
            name='SocialAccountSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('allowed_start_time', models.TimeField(blank=True, null=True)),
                ('allowed_end_time', models.TimeField(blank=True, null=True)),
                ('daily_post_limit', models.IntegerField(default=10)),
                ('automatic_retry_enabled', models.BooleanField(default=True)),
                ('comments_enabled', models.BooleanField(default=True)),
                ('analytics_enabled', models.BooleanField(default=True)),
                ('publishing_paused', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='social_accounts.socialconnection')),
            ],
            options={
                'db_table': 'social_account_settings',
            },
        ),
        migrations.CreateModel(
            name='SocialAccountAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ACCOUNT_CONNECTION', 'Account Connection'), ('OAUTH_AUTHORIZATION', 'OAuth Authorization'), ('PERMISSION_UPDATE', 'Permission Update'), ('TOKEN_REFRESH', 'Token Refresh'), ('ACCOUNT_RECONNECTION', 'Account Reconnection'), ('ACCOUNT_DISCONNECTION', 'Account Disconnection'), ('ACCESS_REVOCATION', 'Access Revocation'), ('PUBLISHING_ENABLED', 'Publishing Enabled'), ('PUBLISHING_DISABLED', 'Publishing Disabled'), ('PUBLISHING_PAUSED', 'Publishing Paused'), ('PUBLISHING_RESUMED', 'Publishing Resumed')], max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_audit_logs', to='workspaces.marketingworkspace')),
                ('social_connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='social_accounts.socialconnection')),
            ],
            options={
                'db_table': 'social_account_audit_logs',
            },
        ),
    ]
