# Generated by Django 6.1 on 2026-08-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('task_path', models.CharField(max_length=255)),
                ('args', models.JSONField(blank=True, default=list)),
                ('kwargs', models.JSONField(blank=True, default=dict)),
                ('queue_name', models.CharField(default='default', max_length=64)),
                ('priority', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('SUCCESSFUL', 'Successful')], default='READY', max_length=20)),
                ('run_after', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('worker_ids', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('return_value', models.JSONField(blank=True, null=True)),
                ('enqueued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task_runs',
                'ordering': ['-enqueued_at'],
                'indexes': [models.Index(fields=['status', 'queue_name', 'run_after'], name='task_runs_status_4db6a0_idx'), models.Index(fields=['status', '-priority', 'enqueued_at'], name='task_runs_status_abe951_idx')],
            },
        ),
    ]
